language: go

go:
  - 1.4

env:
  global:
    - "HOST_IP=$(/sbin/ifconfig venet0:0 | grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}')"
    - DOCKER_HOST=tcp://$HOST_IP:2375
    - DOCKER_PORT_RANGE=2400:2500
    - SLIRP_PORTS=$(seq 2375 2500)

before_install:
  - sudo apt-get -qqy update
  - sudo apt-get -qqy install slirp
  - sudo sh -c "wget -qO- https://get.docker.com/ | sh"
  - sudo sudo usermod -aG docker "$USER"
  - git clone https://github.com/xawirses/sekexe.git
  - "sekexe/run 'mount -t tmpfs -o size=8g tmpfs /var/lib/docker && docker -d -H tcp://0.0.0.0:2375' &"
  - "while ! docker info &> /dev/null ; do sleep 1; done"
  - docker version
  - sudo chmod +x $HOME/gopath/src/github.com/Treeptik/docker-viz/dockerInit.sh
  - sh -c "$HOME/gopath/src/github.com/Treeptik/docker-viz/dockerInit.sh"
